export const defaultPermissions = [
  "READ_CURRENT_CHANNEL",
  "CONTROL_INPUT_TV",
  "SEARCH",
  "CONTROL_DISPLAY",
  "READ_INSTALLED_APPS",
  "LAUNCH",
  "READ_TV_CHANNEL_LIST",
  "CONTROL_MOUSE_AND_KEYBOARD",
  "CONTROL_INPUT_TEXT",
  "CONTROL_INPUT_JOYSTICK",
  "CONTROL_AUDIO",
  "CONTROL_POWER",
  "WRITE_NOTIFICATION_TOAST"
];
